server:
  port: 0

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://172.21.0.1:27017
      repositories:
        type: AUTO
      database: mutant
eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    com.mercadolibre.exam.mutant: DEBUG
    org.springframework.integration: info
    org.springframework.data.mongodb: info
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG