# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use;
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  data:
    mongodb:
      uri: mongodb+srv://mercadolibre-mutante:${mongodbpsw}@cluster0-7wzro.mongodb.net/test?retryWrites=true
      repositories:
        type: AUTO
      database: mutant

#server:
#  port: 8080

logging:
  level:
    root: info
    org.springframework.integration: info
    org.springframework.data.mongodb: info

